apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: phppgadmin
  name: phppgadmin
spec:
  output:
    to:
      kind: ImageStreamTag
      name: phppgadmin:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-phpPgAdmin.git
    contextDir: phpPgAdmin/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: php-webserver:latest
        namespace: weepee-registry
    type: Docker
